#!/usr/bin/env python3

import pathlib
import subprocess


def main():
    dockerfile_path = pathlib.Path(__file__).absolute().parent.parent
    subprocess.call(["docker", "build", ".", "-t", "singularitynet/example-service:latest"], cwd=dockerfile_path)


if __name__ == "__main__":
    main()
