#!/usr/bin/env python3

import pathlib
import subprocess
import signal
import time


def main():
    def handle_signal(signum, frame):
        snetd_p.send_signal(signum)
        service_p.send_signal(signum)
        snetd_p.wait()
        service_p.wait()
        exit(0)

    signal.signal(signal.SIGTERM, handle_signal)
    signal.signal(signal.SIGINT, handle_signal)

    root_path = pathlib.Path(__file__).absolute().parent.parent
    snetd_p = start_snetd(root_path)
    service_p = start_service(root_path)

    while True:
        if snetd_p.poll() is not None:
            snetd_p = start_snetd(root_path)
        if service_p.poll() is not None:
            service_p = start_service(root_path)
        time.sleep(5)


def start_snetd(cwd):
    return subprocess.Popen(["./snetd-linux-amd64"], cwd=cwd)


def start_service(cwd):
    return subprocess.Popen(["python3.6", "image_classification_service"], cwd=cwd)


if __name__ == "__main__":
    main()
